---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metagpu-device-plugin-config
  namespace: cnvrg
data:
  config.yaml: |
    metaGpus: 2
    accelerator: nvidia
    processesDiscoveryPeriod: 5
    deviceCacheTTL: 3600
    resourceName: cnvrg.io/metagpu
    jwtSecret: topSecret
    mgctlTar: /tmp/mgctl
    mgctlAutoInject: true
    autoReshare: true
    serverAddr: 0.0.0.0:50052
    memoryEnforcer: true
