apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "metagpu.fullname" . }}
  labels:
    {{- include "metagpu.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "metagpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "metagpu.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      hostNetwork: true
      serviceAccountName: {{ include "metagpu.serviceAccountName" . }}
      containers:
        - name: metagpu-device-plugin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/mgdp
            - start
            - -c
            - /etc/metagpu-device-plugin
          ports:
            - containerPort: 50052
              name: grpc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: METAGPU_DEVICE_PLUGIN_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MG_CTL_TOKEN
              value: {{ .Values.config.grpcSecurity.deviceToken | quote }}
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: config
              mountPath: /etc/metagpu-device-plugin
            - name: proc
              mountPath: /host/proc
              mountPropagation: HostToContainer
              readOnly: true
        - name: metagpu-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/mgex
            - start
            - -t
            - {{ .Values.config.grpcSecurity.deviceToken | quote }}
          ports:
            - name: metrics
              containerPort: 2112
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: config
          configMap:
            name: {{ include "metagpu.fullname" . }}-config
        - name: proc
          hostPath:
            path: /proc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      