apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metagpu-exporter
  namespace: kube-system
  labels:
    app: "metagpu-exporter"
spec:
  selector:
    matchLabels:
      app: "metagpu-exporter"
  namespaceSelector:
    matchNames:
      - cnvrg
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: "15s"