apiVersion: v1
kind: Service
metadata:
  name: {{ include "metagpu.fullname" . }}
  labels:
    {{- include "metagpu.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 50052
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 2112
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "metagpu.selectorLabels" . | nindent 4 }}
