{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "metagpu.fullname" . }}-exporter
  labels:
    {{- include "metagpu.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels -}}
    {{ toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "metagpu.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: {{ .Values.serviceMonitor.interval | quote }}
{{- end -}}