apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-test
spec:
  selector:
    matchLabels:
      app: gpu-test
  replicas: 1
  template:
    metadata:
      labels:
        app: gpu-test
    spec:
      containers:
      - name: gpu-test
        image: tensorflow/tensorflow:latest-gpu
        command:
          - /usr/local/bin/python
          - -c
          - |
            import tensorflow as tf
            import time
            tf.get_logger().setLevel('INFO')
            print("===============================",flush=True)
            print(tf.config.list_physical_devices('GPU'),flush=True)
            print("===============================",flush=True)
            time.sleep(3600)
