apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metagpu-device-plugin
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metagpu-device-plugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metagpu-device-plugin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metagpu-device-plugin
subjects:
  - kind: ServiceAccount
    name: metagpu-device-plugin
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metagpu-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: metagpu-device-plugin
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: metagpu-device-plugin
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      imagePullSecrets:
        - name: regcred
      hostPID: true
      serviceAccountName: metagpu-device-plugin
      containers:
        - name: metagpu-device-plugin
          image: docker.io/cnvrg/metagpu-device-plugin:latest
          command:
            - /usr/bin/metagpu-device-plugin
            - start
            - -c
            - /etc/metagpu-device-plugin
          ports:
            - containerPort: 50052
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: config
              mountPath: /etc/metagpu-device-plugin
            - mountPath: /host/proc
              mountPropagation: HostToContainer
              name: proc
              readOnly: true
            - mountPath: /var/run/docker.sock
              name: docker
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: config
          configMap:
            name: metagpu-device-plugin-config
        - hostPath:
            path: /proc
          name: proc
        - hostPath:
            path: /var/run/docker.sock
          name: docker
---
kind: Service
apiVersion: v1
metadata:
  name: metagpu-device-plugin
  namespace: kube-system
spec:
  selector:
    name: metagpu-device-plugin
  ports:
    - protocol: TCP
      port: 50052
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metagpu-device-plugin-config
  namespace: kube-system
data:
  config.yaml: |
    metaGpus: 10
    accelerator: nvidia
    processesDiscoveryPeriod: 5
    deviceCacheTTL: 3600
    resourceName: cnvrg.io/metagpu
    jwtSecret: topSecret
    mgctlTar: /tmp/mgctl.tar.gz
    mgctlAutoInject: true
