accelerator: nvidia
processesDiscoveryPeriod: 5
deviceCacheTTL: 3600
jwtSecret: topSecret
mgctlTar: /tmp/mgctl
mgctlAutoInject: true
autoReshare: true
serverAddr: 0.0.0.0:50052
memoryEnforcer: true
deviceIds:
  - uuid: *
    resourceName: cnvrg.io/metagpu
    metaGpus: 2